package com.iotexample.demo.dao;

import com.iotexample.demo.model.Ct;
import com.iotexample.demo.model.CtExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    long countByExample(CtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    int deleteByExample(CtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long ctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    int insert(Ct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    int insertSelective(Ct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    List<Ct> selectByExampleWithRowbounds(CtExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    List<Ct> selectByExample(CtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    Ct selectByPrimaryKey(Long ctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Ct record, @Param("example") CtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Ct record, @Param("example") CtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ct record);
}