package com.iotexample.demo.dao;

import com.iotexample.demo.model.Examinationorder;
import com.iotexample.demo.model.ExaminationorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ExaminationorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    long countByExample(ExaminationorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    int deleteByExample(ExaminationorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long examinationorderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    int insert(Examinationorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    int insertSelective(Examinationorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    List<Examinationorder> selectByExampleWithRowbounds(ExaminationorderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    List<Examinationorder> selectByExample(ExaminationorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    Examinationorder selectByPrimaryKey(Long examinationorderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Examinationorder record, @Param("example") ExaminationorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Examinationorder record, @Param("example") ExaminationorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Examinationorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Examinationorder record);
}