package com.iotexample.demo.dao;

import com.iotexample.demo.model.Guahao;
import com.iotexample.demo.model.GuahaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuahaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    long countByExample(GuahaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    int deleteByExample(GuahaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer guahaoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    int insert(Guahao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    int insertSelective(Guahao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    List<Guahao> selectByExample(GuahaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    Guahao selectByPrimaryKey(Integer guahaoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Guahao record, @Param("example") GuahaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Guahao record, @Param("example") GuahaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Guahao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guahao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Guahao record);
}