package com.iotexample.demo.dao;

import com.iotexample.demo.model.Jianchaorder;
import com.iotexample.demo.model.JianchaorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface JianchaorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    long countByExample(JianchaorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    int deleteByExample(JianchaorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long jianchaorderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    int insert(Jianchaorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    int insertSelective(Jianchaorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    List<Jianchaorder> selectByExampleWithRowbounds(JianchaorderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    List<Jianchaorder> selectByExample(JianchaorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    Jianchaorder selectByPrimaryKey(Long jianchaorderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Jianchaorder record, @Param("example") JianchaorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Jianchaorder record, @Param("example") JianchaorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Jianchaorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Jianchaorder record);
}