package com.iotexample.demo.dao;

import com.iotexample.demo.model.Jiuzhen;
import com.iotexample.demo.model.JiuzhenExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface JiuzhenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    long countByExample(JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int deleteByExample(JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long jiuzhenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int insert(Jiuzhen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int insertSelective(Jiuzhen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    List<Jiuzhen> selectByExampleWithBLOBsWithRowbounds(JiuzhenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    List<Jiuzhen> selectByExampleWithBLOBs(JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    List<Jiuzhen> selectByExampleWithRowbounds(JiuzhenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    List<Jiuzhen> selectByExample(JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    Jiuzhen selectByPrimaryKey(Long jiuzhenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Jiuzhen record, @Param("example") JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Jiuzhen record, @Param("example") JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Jiuzhen record, @Param("example") JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Jiuzhen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Jiuzhen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Jiuzhen record);
}