package com.iotexample.demo.dao;

import com.iotexample.demo.model.Jiuzhen;
import com.iotexample.demo.model.JiuzhenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JiuzhenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    long countByExample(JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int deleteByExample(JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer jiuzhenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int insert(Jiuzhen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int insertSelective(Jiuzhen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    List<Jiuzhen> selectByExample(JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    Jiuzhen selectByPrimaryKey(Integer jiuzhenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Jiuzhen record, @Param("example") JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Jiuzhen record, @Param("example") JiuzhenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Jiuzhen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Jiuzhen record);
}