package com.iotexample.demo.dao;

import com.iotexample.demo.model.Medicalrecord;
import com.iotexample.demo.model.MedicalrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface MedicalrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    long countByExample(MedicalrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    int deleteByExample(MedicalrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long medicalrecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    int insert(Medicalrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    int insertSelective(Medicalrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    List<Medicalrecord> selectByExampleWithRowbounds(MedicalrecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    List<Medicalrecord> selectByExample(MedicalrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    Medicalrecord selectByPrimaryKey(Long medicalrecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Medicalrecord record, @Param("example") MedicalrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Medicalrecord record, @Param("example") MedicalrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Medicalrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicalrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Medicalrecord record);
}