package com.iotexample.demo.dao;

import com.iotexample.demo.model.TreatmentDrugOrder;
import com.iotexample.demo.model.TreatmentDrugOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TreatmentDrugOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    long countByExample(TreatmentDrugOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    int deleteByExample(TreatmentDrugOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long treatmentDrugOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    int insert(TreatmentDrugOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    int insertSelective(TreatmentDrugOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    List<TreatmentDrugOrder> selectByExampleWithRowbounds(TreatmentDrugOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    List<TreatmentDrugOrder> selectByExample(TreatmentDrugOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    TreatmentDrugOrder selectByPrimaryKey(Long treatmentDrugOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TreatmentDrugOrder record, @Param("example") TreatmentDrugOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TreatmentDrugOrder record, @Param("example") TreatmentDrugOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TreatmentDrugOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TreatmentDrugOrder record);
}