package com.iotexample.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CtExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ct
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ct
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ct
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public CtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCtIdIsNull() {
            addCriterion("ct_id is null");
            return (Criteria) this;
        }

        public Criteria andCtIdIsNotNull() {
            addCriterion("ct_id is not null");
            return (Criteria) this;
        }

        public Criteria andCtIdEqualTo(Long value) {
            addCriterion("ct_id =", value, "ctId");
            return (Criteria) this;
        }

        public Criteria andCtIdNotEqualTo(Long value) {
            addCriterion("ct_id <>", value, "ctId");
            return (Criteria) this;
        }

        public Criteria andCtIdGreaterThan(Long value) {
            addCriterion("ct_id >", value, "ctId");
            return (Criteria) this;
        }

        public Criteria andCtIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ct_id >=", value, "ctId");
            return (Criteria) this;
        }

        public Criteria andCtIdLessThan(Long value) {
            addCriterion("ct_id <", value, "ctId");
            return (Criteria) this;
        }

        public Criteria andCtIdLessThanOrEqualTo(Long value) {
            addCriterion("ct_id <=", value, "ctId");
            return (Criteria) this;
        }

        public Criteria andCtIdIn(List<Long> values) {
            addCriterion("ct_id in", values, "ctId");
            return (Criteria) this;
        }

        public Criteria andCtIdNotIn(List<Long> values) {
            addCriterion("ct_id not in", values, "ctId");
            return (Criteria) this;
        }

        public Criteria andCtIdBetween(Long value1, Long value2) {
            addCriterion("ct_id between", value1, value2, "ctId");
            return (Criteria) this;
        }

        public Criteria andCtIdNotBetween(Long value1, Long value2) {
            addCriterion("ct_id not between", value1, value2, "ctId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCtTimeIsNull() {
            addCriterion("ct_time is null");
            return (Criteria) this;
        }

        public Criteria andCtTimeIsNotNull() {
            addCriterion("ct_time is not null");
            return (Criteria) this;
        }

        public Criteria andCtTimeEqualTo(Date value) {
            addCriterion("ct_time =", value, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtTimeNotEqualTo(Date value) {
            addCriterion("ct_time <>", value, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtTimeGreaterThan(Date value) {
            addCriterion("ct_time >", value, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ct_time >=", value, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtTimeLessThan(Date value) {
            addCriterion("ct_time <", value, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtTimeLessThanOrEqualTo(Date value) {
            addCriterion("ct_time <=", value, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtTimeIn(List<Date> values) {
            addCriterion("ct_time in", values, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtTimeNotIn(List<Date> values) {
            addCriterion("ct_time not in", values, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtTimeBetween(Date value1, Date value2) {
            addCriterion("ct_time between", value1, value2, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtTimeNotBetween(Date value1, Date value2) {
            addCriterion("ct_time not between", value1, value2, "ctTime");
            return (Criteria) this;
        }

        public Criteria andCtAddrIsNull() {
            addCriterion("ct_addr is null");
            return (Criteria) this;
        }

        public Criteria andCtAddrIsNotNull() {
            addCriterion("ct_addr is not null");
            return (Criteria) this;
        }

        public Criteria andCtAddrEqualTo(String value) {
            addCriterion("ct_addr =", value, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrNotEqualTo(String value) {
            addCriterion("ct_addr <>", value, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrGreaterThan(String value) {
            addCriterion("ct_addr >", value, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ct_addr >=", value, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrLessThan(String value) {
            addCriterion("ct_addr <", value, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrLessThanOrEqualTo(String value) {
            addCriterion("ct_addr <=", value, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrLike(String value) {
            addCriterion("ct_addr like", value, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrNotLike(String value) {
            addCriterion("ct_addr not like", value, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrIn(List<String> values) {
            addCriterion("ct_addr in", values, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrNotIn(List<String> values) {
            addCriterion("ct_addr not in", values, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrBetween(String value1, String value2) {
            addCriterion("ct_addr between", value1, value2, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtAddrNotBetween(String value1, String value2) {
            addCriterion("ct_addr not between", value1, value2, "ctAddr");
            return (Criteria) this;
        }

        public Criteria andCtCostIsNull() {
            addCriterion("ct_cost is null");
            return (Criteria) this;
        }

        public Criteria andCtCostIsNotNull() {
            addCriterion("ct_cost is not null");
            return (Criteria) this;
        }

        public Criteria andCtCostEqualTo(BigDecimal value) {
            addCriterion("ct_cost =", value, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtCostNotEqualTo(BigDecimal value) {
            addCriterion("ct_cost <>", value, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtCostGreaterThan(BigDecimal value) {
            addCriterion("ct_cost >", value, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ct_cost >=", value, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtCostLessThan(BigDecimal value) {
            addCriterion("ct_cost <", value, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ct_cost <=", value, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtCostIn(List<BigDecimal> values) {
            addCriterion("ct_cost in", values, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtCostNotIn(List<BigDecimal> values) {
            addCriterion("ct_cost not in", values, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ct_cost between", value1, value2, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ct_cost not between", value1, value2, "ctCost");
            return (Criteria) this;
        }

        public Criteria andCtReportIsNull() {
            addCriterion("ct_report is null");
            return (Criteria) this;
        }

        public Criteria andCtReportIsNotNull() {
            addCriterion("ct_report is not null");
            return (Criteria) this;
        }

        public Criteria andCtReportEqualTo(String value) {
            addCriterion("ct_report =", value, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportNotEqualTo(String value) {
            addCriterion("ct_report <>", value, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportGreaterThan(String value) {
            addCriterion("ct_report >", value, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportGreaterThanOrEqualTo(String value) {
            addCriterion("ct_report >=", value, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportLessThan(String value) {
            addCriterion("ct_report <", value, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportLessThanOrEqualTo(String value) {
            addCriterion("ct_report <=", value, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportLike(String value) {
            addCriterion("ct_report like", value, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportNotLike(String value) {
            addCriterion("ct_report not like", value, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportIn(List<String> values) {
            addCriterion("ct_report in", values, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportNotIn(List<String> values) {
            addCriterion("ct_report not in", values, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportBetween(String value1, String value2) {
            addCriterion("ct_report between", value1, value2, "ctReport");
            return (Criteria) this;
        }

        public Criteria andCtReportNotBetween(String value1, String value2) {
            addCriterion("ct_report not between", value1, value2, "ctReport");
            return (Criteria) this;
        }

        public Criteria andReportTimeIsNull() {
            addCriterion("report_time is null");
            return (Criteria) this;
        }

        public Criteria andReportTimeIsNotNull() {
            addCriterion("report_time is not null");
            return (Criteria) this;
        }

        public Criteria andReportTimeEqualTo(Date value) {
            addCriterion("report_time =", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeNotEqualTo(Date value) {
            addCriterion("report_time <>", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeGreaterThan(Date value) {
            addCriterion("report_time >", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("report_time >=", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeLessThan(Date value) {
            addCriterion("report_time <", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeLessThanOrEqualTo(Date value) {
            addCriterion("report_time <=", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeIn(List<Date> values) {
            addCriterion("report_time in", values, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeNotIn(List<Date> values) {
            addCriterion("report_time not in", values, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeBetween(Date value1, Date value2) {
            addCriterion("report_time between", value1, value2, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeNotBetween(Date value1, Date value2) {
            addCriterion("report_time not between", value1, value2, "reportTime");
            return (Criteria) this;
        }

        public Criteria andCtImgIsNull() {
            addCriterion("ct_img is null");
            return (Criteria) this;
        }

        public Criteria andCtImgIsNotNull() {
            addCriterion("ct_img is not null");
            return (Criteria) this;
        }

        public Criteria andCtImgEqualTo(String value) {
            addCriterion("ct_img =", value, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgNotEqualTo(String value) {
            addCriterion("ct_img <>", value, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgGreaterThan(String value) {
            addCriterion("ct_img >", value, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgGreaterThanOrEqualTo(String value) {
            addCriterion("ct_img >=", value, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgLessThan(String value) {
            addCriterion("ct_img <", value, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgLessThanOrEqualTo(String value) {
            addCriterion("ct_img <=", value, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgLike(String value) {
            addCriterion("ct_img like", value, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgNotLike(String value) {
            addCriterion("ct_img not like", value, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgIn(List<String> values) {
            addCriterion("ct_img in", values, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgNotIn(List<String> values) {
            addCriterion("ct_img not in", values, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgBetween(String value1, String value2) {
            addCriterion("ct_img between", value1, value2, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtImgNotBetween(String value1, String value2) {
            addCriterion("ct_img not between", value1, value2, "ctImg");
            return (Criteria) this;
        }

        public Criteria andCtPartIsNull() {
            addCriterion("ct_part is null");
            return (Criteria) this;
        }

        public Criteria andCtPartIsNotNull() {
            addCriterion("ct_part is not null");
            return (Criteria) this;
        }

        public Criteria andCtPartEqualTo(String value) {
            addCriterion("ct_part =", value, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartNotEqualTo(String value) {
            addCriterion("ct_part <>", value, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartGreaterThan(String value) {
            addCriterion("ct_part >", value, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartGreaterThanOrEqualTo(String value) {
            addCriterion("ct_part >=", value, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartLessThan(String value) {
            addCriterion("ct_part <", value, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartLessThanOrEqualTo(String value) {
            addCriterion("ct_part <=", value, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartLike(String value) {
            addCriterion("ct_part like", value, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartNotLike(String value) {
            addCriterion("ct_part not like", value, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartIn(List<String> values) {
            addCriterion("ct_part in", values, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartNotIn(List<String> values) {
            addCriterion("ct_part not in", values, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartBetween(String value1, String value2) {
            addCriterion("ct_part between", value1, value2, "ctPart");
            return (Criteria) this;
        }

        public Criteria andCtPartNotBetween(String value1, String value2) {
            addCriterion("ct_part not between", value1, value2, "ctPart");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}