package com.iotexample.demo.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Department implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_id
     *
     * @mbg.generated
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_name
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_addr
     *
     * @mbg.generated
     */
    private String departmentAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.hospital_id
     *
     * @mbg.generated
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_cost
     *
     * @mbg.generated
     */
    private BigDecimal departmentCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_id
     *
     * @return the value of department.department_id
     *
     * @mbg.generated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_id
     *
     * @param departmentId the value for department.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_name
     *
     * @return the value of department.department_name
     *
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_name
     *
     * @param departmentName the value for department.department_name
     *
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_addr
     *
     * @return the value of department.department_addr
     *
     * @mbg.generated
     */
    public String getDepartmentAddr() {
        return departmentAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_addr
     *
     * @param departmentAddr the value for department.department_addr
     *
     * @mbg.generated
     */
    public void setDepartmentAddr(String departmentAddr) {
        this.departmentAddr = departmentAddr == null ? null : departmentAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.hospital_id
     *
     * @return the value of department.hospital_id
     *
     * @mbg.generated
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.hospital_id
     *
     * @param hospitalId the value for department.hospital_id
     *
     * @mbg.generated
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.hospital_name
     *
     * @return the value of department.hospital_name
     *
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.hospital_name
     *
     * @param hospitalName the value for department.hospital_name
     *
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_cost
     *
     * @return the value of department.department_cost
     *
     * @mbg.generated
     */
    public BigDecimal getDepartmentCost() {
        return departmentCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_cost
     *
     * @param departmentCost the value for department.department_cost
     *
     * @mbg.generated
     */
    public void setDepartmentCost(BigDecimal departmentCost) {
        this.departmentCost = departmentCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", departmentId=").append(departmentId);
        sb.append(", departmentName=").append(departmentName);
        sb.append(", departmentAddr=").append(departmentAddr);
        sb.append(", hospitalId=").append(hospitalId);
        sb.append(", hospitalName=").append(hospitalName);
        sb.append(", departmentCost=").append(departmentCost);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}