package com.iotexample.demo.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Drug implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.drug_id
     *
     * @mbg.generated
     */
    private Long drugId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.drug_type
     *
     * @mbg.generated
     */
    private String drugType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.drug_name
     *
     * @mbg.generated
     */
    private String drugName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.production_place
     *
     * @mbg.generated
     */
    private String productionPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.drug_price
     *
     * @mbg.generated
     */
    private BigDecimal drugPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.drug_stock
     *
     * @mbg.generated
     */
    private Integer drugStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.drug_id
     *
     * @return the value of drug.drug_id
     *
     * @mbg.generated
     */
    public Long getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated
     */
    public Drug withDrugId(Long drugId) {
        this.setDrugId(drugId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.drug_id
     *
     * @param drugId the value for drug.drug_id
     *
     * @mbg.generated
     */
    public void setDrugId(Long drugId) {
        this.drugId = drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.drug_type
     *
     * @return the value of drug.drug_type
     *
     * @mbg.generated
     */
    public String getDrugType() {
        return drugType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated
     */
    public Drug withDrugType(String drugType) {
        this.setDrugType(drugType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.drug_type
     *
     * @param drugType the value for drug.drug_type
     *
     * @mbg.generated
     */
    public void setDrugType(String drugType) {
        this.drugType = drugType == null ? null : drugType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.drug_name
     *
     * @return the value of drug.drug_name
     *
     * @mbg.generated
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated
     */
    public Drug withDrugName(String drugName) {
        this.setDrugName(drugName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.drug_name
     *
     * @param drugName the value for drug.drug_name
     *
     * @mbg.generated
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName == null ? null : drugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.production_place
     *
     * @return the value of drug.production_place
     *
     * @mbg.generated
     */
    public String getProductionPlace() {
        return productionPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated
     */
    public Drug withProductionPlace(String productionPlace) {
        this.setProductionPlace(productionPlace);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.production_place
     *
     * @param productionPlace the value for drug.production_place
     *
     * @mbg.generated
     */
    public void setProductionPlace(String productionPlace) {
        this.productionPlace = productionPlace == null ? null : productionPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.drug_price
     *
     * @return the value of drug.drug_price
     *
     * @mbg.generated
     */
    public BigDecimal getDrugPrice() {
        return drugPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated
     */
    public Drug withDrugPrice(BigDecimal drugPrice) {
        this.setDrugPrice(drugPrice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.drug_price
     *
     * @param drugPrice the value for drug.drug_price
     *
     * @mbg.generated
     */
    public void setDrugPrice(BigDecimal drugPrice) {
        this.drugPrice = drugPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.drug_stock
     *
     * @return the value of drug.drug_stock
     *
     * @mbg.generated
     */
    public Integer getDrugStock() {
        return drugStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated
     */
    public Drug withDrugStock(Integer drugStock) {
        this.setDrugStock(drugStock);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.drug_stock
     *
     * @param drugStock the value for drug.drug_stock
     *
     * @mbg.generated
     */
    public void setDrugStock(Integer drugStock) {
        this.drugStock = drugStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.create_date
     *
     * @return the value of drug.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated
     */
    public Drug withCreateDate(Date createDate) {
        this.setCreateDate(createDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.create_date
     *
     * @param createDate the value for drug.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", drugId=").append(drugId);
        sb.append(", drugType=").append(drugType);
        sb.append(", drugName=").append(drugName);
        sb.append(", productionPlace=").append(productionPlace);
        sb.append(", drugPrice=").append(drugPrice);
        sb.append(", drugStock=").append(drugStock);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}