package com.iotexample.demo.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Examinationorder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.examinationOrder_id
     *
     * @mbg.generated
     */
    private Long examinationorderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.medicalRecord_id
     *
     * @mbg.generated
     */
    private Long medicalrecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.examination_id
     *
     * @mbg.generated
     */
    private Long examinationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.examination_type
     *
     * @mbg.generated
     */
    private String examinationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.examination_type_id
     *
     * @mbg.generated
     */
    private Long examinationTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.pay_state
     *
     * @mbg.generated
     */
    private Integer payState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.examination_cost
     *
     * @mbg.generated
     */
    private BigDecimal examinationCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinationorder.active
     *
     * @mbg.generated
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.examinationOrder_id
     *
     * @return the value of examinationorder.examinationOrder_id
     *
     * @mbg.generated
     */
    public Long getExaminationorderId() {
        return examinationorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withExaminationorderId(Long examinationorderId) {
        this.setExaminationorderId(examinationorderId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.examinationOrder_id
     *
     * @param examinationorderId the value for examinationorder.examinationOrder_id
     *
     * @mbg.generated
     */
    public void setExaminationorderId(Long examinationorderId) {
        this.examinationorderId = examinationorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.user_id
     *
     * @return the value of examinationorder.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.user_id
     *
     * @param userId the value for examinationorder.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.medicalRecord_id
     *
     * @return the value of examinationorder.medicalRecord_id
     *
     * @mbg.generated
     */
    public Long getMedicalrecordId() {
        return medicalrecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withMedicalrecordId(Long medicalrecordId) {
        this.setMedicalrecordId(medicalrecordId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.medicalRecord_id
     *
     * @param medicalrecordId the value for examinationorder.medicalRecord_id
     *
     * @mbg.generated
     */
    public void setMedicalrecordId(Long medicalrecordId) {
        this.medicalrecordId = medicalrecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.examination_id
     *
     * @return the value of examinationorder.examination_id
     *
     * @mbg.generated
     */
    public Long getExaminationId() {
        return examinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withExaminationId(Long examinationId) {
        this.setExaminationId(examinationId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.examination_id
     *
     * @param examinationId the value for examinationorder.examination_id
     *
     * @mbg.generated
     */
    public void setExaminationId(Long examinationId) {
        this.examinationId = examinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.examination_type
     *
     * @return the value of examinationorder.examination_type
     *
     * @mbg.generated
     */
    public String getExaminationType() {
        return examinationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withExaminationType(String examinationType) {
        this.setExaminationType(examinationType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.examination_type
     *
     * @param examinationType the value for examinationorder.examination_type
     *
     * @mbg.generated
     */
    public void setExaminationType(String examinationType) {
        this.examinationType = examinationType == null ? null : examinationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.examination_type_id
     *
     * @return the value of examinationorder.examination_type_id
     *
     * @mbg.generated
     */
    public Long getExaminationTypeId() {
        return examinationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withExaminationTypeId(Long examinationTypeId) {
        this.setExaminationTypeId(examinationTypeId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.examination_type_id
     *
     * @param examinationTypeId the value for examinationorder.examination_type_id
     *
     * @mbg.generated
     */
    public void setExaminationTypeId(Long examinationTypeId) {
        this.examinationTypeId = examinationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.pay_state
     *
     * @return the value of examinationorder.pay_state
     *
     * @mbg.generated
     */
    public Integer getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withPayState(Integer payState) {
        this.setPayState(payState);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.pay_state
     *
     * @param payState the value for examinationorder.pay_state
     *
     * @mbg.generated
     */
    public void setPayState(Integer payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.examination_cost
     *
     * @return the value of examinationorder.examination_cost
     *
     * @mbg.generated
     */
    public BigDecimal getExaminationCost() {
        return examinationCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withExaminationCost(BigDecimal examinationCost) {
        this.setExaminationCost(examinationCost);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.examination_cost
     *
     * @param examinationCost the value for examinationorder.examination_cost
     *
     * @mbg.generated
     */
    public void setExaminationCost(BigDecimal examinationCost) {
        this.examinationCost = examinationCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.time
     *
     * @return the value of examinationorder.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withTime(Date time) {
        this.setTime(time);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.time
     *
     * @param time the value for examinationorder.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinationorder.active
     *
     * @return the value of examinationorder.active
     *
     * @mbg.generated
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    public Examinationorder withActive(Integer active) {
        this.setActive(active);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinationorder.active
     *
     * @param active the value for examinationorder.active
     *
     * @mbg.generated
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinationorder
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", examinationorderId=").append(examinationorderId);
        sb.append(", userId=").append(userId);
        sb.append(", medicalrecordId=").append(medicalrecordId);
        sb.append(", examinationId=").append(examinationId);
        sb.append(", examinationType=").append(examinationType);
        sb.append(", examinationTypeId=").append(examinationTypeId);
        sb.append(", payState=").append(payState);
        sb.append(", examinationCost=").append(examinationCost);
        sb.append(", time=").append(time);
        sb.append(", active=").append(active);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}