package com.iotexample.demo.model;

import java.io.Serializable;
import java.util.Date;

public class ExaminationReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination_report.examination_report_id
     *
     * @mbg.generated
     */
    private Long examinationReportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination_report.examinationOrder_id
     *
     * @mbg.generated
     */
    private Long examinationorderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination_report.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination_report.examination_result
     *
     * @mbg.generated
     */
    private String examinationResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examination_report
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination_report.examination_report_id
     *
     * @return the value of examination_report.examination_report_id
     *
     * @mbg.generated
     */
    public Long getExaminationReportId() {
        return examinationReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination_report
     *
     * @mbg.generated
     */
    public ExaminationReport withExaminationReportId(Long examinationReportId) {
        this.setExaminationReportId(examinationReportId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination_report.examination_report_id
     *
     * @param examinationReportId the value for examination_report.examination_report_id
     *
     * @mbg.generated
     */
    public void setExaminationReportId(Long examinationReportId) {
        this.examinationReportId = examinationReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination_report.examinationOrder_id
     *
     * @return the value of examination_report.examinationOrder_id
     *
     * @mbg.generated
     */
    public Long getExaminationorderId() {
        return examinationorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination_report
     *
     * @mbg.generated
     */
    public ExaminationReport withExaminationorderId(Long examinationorderId) {
        this.setExaminationorderId(examinationorderId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination_report.examinationOrder_id
     *
     * @param examinationorderId the value for examination_report.examinationOrder_id
     *
     * @mbg.generated
     */
    public void setExaminationorderId(Long examinationorderId) {
        this.examinationorderId = examinationorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination_report.create_date
     *
     * @return the value of examination_report.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination_report
     *
     * @mbg.generated
     */
    public ExaminationReport withCreateDate(Date createDate) {
        this.setCreateDate(createDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination_report.create_date
     *
     * @param createDate the value for examination_report.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination_report.examination_result
     *
     * @return the value of examination_report.examination_result
     *
     * @mbg.generated
     */
    public String getExaminationResult() {
        return examinationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination_report
     *
     * @mbg.generated
     */
    public ExaminationReport withExaminationResult(String examinationResult) {
        this.setExaminationResult(examinationResult);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination_report.examination_result
     *
     * @param examinationResult the value for examination_report.examination_result
     *
     * @mbg.generated
     */
    public void setExaminationResult(String examinationResult) {
        this.examinationResult = examinationResult == null ? null : examinationResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination_report
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", examinationReportId=").append(examinationReportId);
        sb.append(", examinationorderId=").append(examinationorderId);
        sb.append(", createDate=").append(createDate);
        sb.append(", examinationResult=").append(examinationResult);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}