package com.iotexample.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class JianchaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public JianchaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJianchaIdIsNull() {
            addCriterion("jiancha_id is null");
            return (Criteria) this;
        }

        public Criteria andJianchaIdIsNotNull() {
            addCriterion("jiancha_id is not null");
            return (Criteria) this;
        }

        public Criteria andJianchaIdEqualTo(Long value) {
            addCriterion("jiancha_id =", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdNotEqualTo(Long value) {
            addCriterion("jiancha_id <>", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdGreaterThan(Long value) {
            addCriterion("jiancha_id >", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("jiancha_id >=", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdLessThan(Long value) {
            addCriterion("jiancha_id <", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdLessThanOrEqualTo(Long value) {
            addCriterion("jiancha_id <=", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdIn(List<Long> values) {
            addCriterion("jiancha_id in", values, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdNotIn(List<Long> values) {
            addCriterion("jiancha_id not in", values, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdBetween(Long value1, Long value2) {
            addCriterion("jiancha_id between", value1, value2, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdNotBetween(Long value1, Long value2) {
            addCriterion("jiancha_id not between", value1, value2, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaNameIsNull() {
            addCriterion("jiancha_name is null");
            return (Criteria) this;
        }

        public Criteria andJianchaNameIsNotNull() {
            addCriterion("jiancha_name is not null");
            return (Criteria) this;
        }

        public Criteria andJianchaNameEqualTo(String value) {
            addCriterion("jiancha_name =", value, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameNotEqualTo(String value) {
            addCriterion("jiancha_name <>", value, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameGreaterThan(String value) {
            addCriterion("jiancha_name >", value, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameGreaterThanOrEqualTo(String value) {
            addCriterion("jiancha_name >=", value, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameLessThan(String value) {
            addCriterion("jiancha_name <", value, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameLessThanOrEqualTo(String value) {
            addCriterion("jiancha_name <=", value, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameLike(String value) {
            addCriterion("jiancha_name like", value, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameNotLike(String value) {
            addCriterion("jiancha_name not like", value, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameIn(List<String> values) {
            addCriterion("jiancha_name in", values, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameNotIn(List<String> values) {
            addCriterion("jiancha_name not in", values, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameBetween(String value1, String value2) {
            addCriterion("jiancha_name between", value1, value2, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaNameNotBetween(String value1, String value2) {
            addCriterion("jiancha_name not between", value1, value2, "jianchaName");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrIsNull() {
            addCriterion("jiancha_addr is null");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrIsNotNull() {
            addCriterion("jiancha_addr is not null");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrEqualTo(String value) {
            addCriterion("jiancha_addr =", value, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrNotEqualTo(String value) {
            addCriterion("jiancha_addr <>", value, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrGreaterThan(String value) {
            addCriterion("jiancha_addr >", value, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrGreaterThanOrEqualTo(String value) {
            addCriterion("jiancha_addr >=", value, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrLessThan(String value) {
            addCriterion("jiancha_addr <", value, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrLessThanOrEqualTo(String value) {
            addCriterion("jiancha_addr <=", value, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrLike(String value) {
            addCriterion("jiancha_addr like", value, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrNotLike(String value) {
            addCriterion("jiancha_addr not like", value, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrIn(List<String> values) {
            addCriterion("jiancha_addr in", values, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrNotIn(List<String> values) {
            addCriterion("jiancha_addr not in", values, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrBetween(String value1, String value2) {
            addCriterion("jiancha_addr between", value1, value2, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaAddrNotBetween(String value1, String value2) {
            addCriterion("jiancha_addr not between", value1, value2, "jianchaAddr");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeIsNull() {
            addCriterion("jiancha_time is null");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeIsNotNull() {
            addCriterion("jiancha_time is not null");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeEqualTo(Integer value) {
            addCriterion("jiancha_time =", value, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeNotEqualTo(Integer value) {
            addCriterion("jiancha_time <>", value, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeGreaterThan(Integer value) {
            addCriterion("jiancha_time >", value, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("jiancha_time >=", value, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeLessThan(Integer value) {
            addCriterion("jiancha_time <", value, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeLessThanOrEqualTo(Integer value) {
            addCriterion("jiancha_time <=", value, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeIn(List<Integer> values) {
            addCriterion("jiancha_time in", values, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeNotIn(List<Integer> values) {
            addCriterion("jiancha_time not in", values, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeBetween(Integer value1, Integer value2) {
            addCriterion("jiancha_time between", value1, value2, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("jiancha_time not between", value1, value2, "jianchaTime");
            return (Criteria) this;
        }

        public Criteria andJianchaCostIsNull() {
            addCriterion("jiancha_cost is null");
            return (Criteria) this;
        }

        public Criteria andJianchaCostIsNotNull() {
            addCriterion("jiancha_cost is not null");
            return (Criteria) this;
        }

        public Criteria andJianchaCostEqualTo(BigDecimal value) {
            addCriterion("jiancha_cost =", value, "jianchaCost");
            return (Criteria) this;
        }

        public Criteria andJianchaCostNotEqualTo(BigDecimal value) {
            addCriterion("jiancha_cost <>", value, "jianchaCost");
            return (Criteria) this;
        }

        public Criteria andJianchaCostGreaterThan(BigDecimal value) {
            addCriterion("jiancha_cost >", value, "jianchaCost");
            return (Criteria) this;
        }

        public Criteria andJianchaCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("jiancha_cost >=", value, "jianchaCost");
            return (Criteria) this;
        }

        public Criteria andJianchaCostLessThan(BigDecimal value) {
            addCriterion("jiancha_cost <", value, "jianchaCost");
            return (Criteria) this;
        }

        public Criteria andJianchaCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("jiancha_cost <=", value, "jianchaCost");
            return (Criteria) this;
        }

        public Criteria andJianchaCostIn(List<BigDecimal> values) {
            addCriterion("jiancha_cost in", values, "jianchaCost");
            return (Criteria) this;
        }

        public Criteria andJianchaCostNotIn(List<BigDecimal> values) {
            addCriterion("jiancha_cost not in", values, "jianchaCost");
            return (Criteria) this;
        }

        public Criteria andJianchaCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jiancha_cost between", value1, value2, "jianchaCost");
            return (Criteria) this;
        }

        public Criteria andJianchaCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jiancha_cost not between", value1, value2, "jianchaCost");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jiancha
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jiancha
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}