package com.iotexample.demo.model;

import java.io.Serializable;
import java.util.Date;

public class Jianchaorder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.jianchaOrder_id
     *
     * @mbg.generated
     */
    private Integer jianchaorderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.jiancha_id
     *
     * @mbg.generated
     */
    private Integer jianchaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.report_id
     *
     * @mbg.generated
     */
    private Integer reportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.jianchaOrder_id
     *
     * @return the value of jianchaorder.jianchaOrder_id
     *
     * @mbg.generated
     */
    public Integer getJianchaorderId() {
        return jianchaorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.jianchaOrder_id
     *
     * @param jianchaorderId the value for jianchaorder.jianchaOrder_id
     *
     * @mbg.generated
     */
    public void setJianchaorderId(Integer jianchaorderId) {
        this.jianchaorderId = jianchaorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.user_id
     *
     * @return the value of jianchaorder.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.user_id
     *
     * @param userId the value for jianchaorder.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.jiancha_id
     *
     * @return the value of jianchaorder.jiancha_id
     *
     * @mbg.generated
     */
    public Integer getJianchaId() {
        return jianchaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.jiancha_id
     *
     * @param jianchaId the value for jianchaorder.jiancha_id
     *
     * @mbg.generated
     */
    public void setJianchaId(Integer jianchaId) {
        this.jianchaId = jianchaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.report_id
     *
     * @return the value of jianchaorder.report_id
     *
     * @mbg.generated
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.report_id
     *
     * @param reportId the value for jianchaorder.report_id
     *
     * @mbg.generated
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.create_date
     *
     * @return the value of jianchaorder.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.create_date
     *
     * @param createDate the value for jianchaorder.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jianchaorderId=").append(jianchaorderId);
        sb.append(", userId=").append(userId);
        sb.append(", jianchaId=").append(jianchaId);
        sb.append(", reportId=").append(reportId);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}