package com.iotexample.demo.model;

import java.io.Serializable;
import java.util.Date;

public class Jianchaorder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.jianchaOrder_id
     *
     * @mbg.generated
     */
    private Long jianchaorderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.jiuzhen_id
     *
     * @mbg.generated
     */
    private Long jiuzhenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.jiancha_id
     *
     * @mbg.generated
     */
    private Long jianchaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.report_id
     *
     * @mbg.generated
     */
    private Long reportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianchaorder.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.jianchaOrder_id
     *
     * @return the value of jianchaorder.jianchaOrder_id
     *
     * @mbg.generated
     */
    public Long getJianchaorderId() {
        return jianchaorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public Jianchaorder withJianchaorderId(Long jianchaorderId) {
        this.setJianchaorderId(jianchaorderId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.jianchaOrder_id
     *
     * @param jianchaorderId the value for jianchaorder.jianchaOrder_id
     *
     * @mbg.generated
     */
    public void setJianchaorderId(Long jianchaorderId) {
        this.jianchaorderId = jianchaorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.user_id
     *
     * @return the value of jianchaorder.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public Jianchaorder withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.user_id
     *
     * @param userId the value for jianchaorder.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.jiuzhen_id
     *
     * @return the value of jianchaorder.jiuzhen_id
     *
     * @mbg.generated
     */
    public Long getJiuzhenId() {
        return jiuzhenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public Jianchaorder withJiuzhenId(Long jiuzhenId) {
        this.setJiuzhenId(jiuzhenId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.jiuzhen_id
     *
     * @param jiuzhenId the value for jianchaorder.jiuzhen_id
     *
     * @mbg.generated
     */
    public void setJiuzhenId(Long jiuzhenId) {
        this.jiuzhenId = jiuzhenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.jiancha_id
     *
     * @return the value of jianchaorder.jiancha_id
     *
     * @mbg.generated
     */
    public Long getJianchaId() {
        return jianchaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public Jianchaorder withJianchaId(Long jianchaId) {
        this.setJianchaId(jianchaId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.jiancha_id
     *
     * @param jianchaId the value for jianchaorder.jiancha_id
     *
     * @mbg.generated
     */
    public void setJianchaId(Long jianchaId) {
        this.jianchaId = jianchaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.report_id
     *
     * @return the value of jianchaorder.report_id
     *
     * @mbg.generated
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public Jianchaorder withReportId(Long reportId) {
        this.setReportId(reportId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.report_id
     *
     * @param reportId the value for jianchaorder.report_id
     *
     * @mbg.generated
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.create_date
     *
     * @return the value of jianchaorder.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public Jianchaorder withCreateDate(Date createDate) {
        this.setCreateDate(createDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.create_date
     *
     * @param createDate the value for jianchaorder.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianchaorder.start_date
     *
     * @return the value of jianchaorder.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public Jianchaorder withStartDate(Date startDate) {
        this.setStartDate(startDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianchaorder.start_date
     *
     * @param startDate the value for jianchaorder.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jianchaorderId=").append(jianchaorderId);
        sb.append(", userId=").append(userId);
        sb.append(", jiuzhenId=").append(jiuzhenId);
        sb.append(", jianchaId=").append(jianchaId);
        sb.append(", reportId=").append(reportId);
        sb.append(", createDate=").append(createDate);
        sb.append(", startDate=").append(startDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}