package com.iotexample.demo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JianchaorderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public JianchaorderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJianchaorderIdIsNull() {
            addCriterion("jianchaOrder_id is null");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdIsNotNull() {
            addCriterion("jianchaOrder_id is not null");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdEqualTo(Long value) {
            addCriterion("jianchaOrder_id =", value, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdNotEqualTo(Long value) {
            addCriterion("jianchaOrder_id <>", value, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdGreaterThan(Long value) {
            addCriterion("jianchaOrder_id >", value, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("jianchaOrder_id >=", value, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdLessThan(Long value) {
            addCriterion("jianchaOrder_id <", value, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdLessThanOrEqualTo(Long value) {
            addCriterion("jianchaOrder_id <=", value, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdIn(List<Long> values) {
            addCriterion("jianchaOrder_id in", values, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdNotIn(List<Long> values) {
            addCriterion("jianchaOrder_id not in", values, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdBetween(Long value1, Long value2) {
            addCriterion("jianchaOrder_id between", value1, value2, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andJianchaorderIdNotBetween(Long value1, Long value2) {
            addCriterion("jianchaOrder_id not between", value1, value2, "jianchaorderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdIsNull() {
            addCriterion("jiuzhen_id is null");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdIsNotNull() {
            addCriterion("jiuzhen_id is not null");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdEqualTo(Long value) {
            addCriterion("jiuzhen_id =", value, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdNotEqualTo(Long value) {
            addCriterion("jiuzhen_id <>", value, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdGreaterThan(Long value) {
            addCriterion("jiuzhen_id >", value, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdGreaterThanOrEqualTo(Long value) {
            addCriterion("jiuzhen_id >=", value, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdLessThan(Long value) {
            addCriterion("jiuzhen_id <", value, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdLessThanOrEqualTo(Long value) {
            addCriterion("jiuzhen_id <=", value, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdIn(List<Long> values) {
            addCriterion("jiuzhen_id in", values, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdNotIn(List<Long> values) {
            addCriterion("jiuzhen_id not in", values, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdBetween(Long value1, Long value2) {
            addCriterion("jiuzhen_id between", value1, value2, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJiuzhenIdNotBetween(Long value1, Long value2) {
            addCriterion("jiuzhen_id not between", value1, value2, "jiuzhenId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdIsNull() {
            addCriterion("jiancha_id is null");
            return (Criteria) this;
        }

        public Criteria andJianchaIdIsNotNull() {
            addCriterion("jiancha_id is not null");
            return (Criteria) this;
        }

        public Criteria andJianchaIdEqualTo(Long value) {
            addCriterion("jiancha_id =", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdNotEqualTo(Long value) {
            addCriterion("jiancha_id <>", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdGreaterThan(Long value) {
            addCriterion("jiancha_id >", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("jiancha_id >=", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdLessThan(Long value) {
            addCriterion("jiancha_id <", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdLessThanOrEqualTo(Long value) {
            addCriterion("jiancha_id <=", value, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdIn(List<Long> values) {
            addCriterion("jiancha_id in", values, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdNotIn(List<Long> values) {
            addCriterion("jiancha_id not in", values, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdBetween(Long value1, Long value2) {
            addCriterion("jiancha_id between", value1, value2, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andJianchaIdNotBetween(Long value1, Long value2) {
            addCriterion("jiancha_id not between", value1, value2, "jianchaId");
            return (Criteria) this;
        }

        public Criteria andReportIdIsNull() {
            addCriterion("report_id is null");
            return (Criteria) this;
        }

        public Criteria andReportIdIsNotNull() {
            addCriterion("report_id is not null");
            return (Criteria) this;
        }

        public Criteria andReportIdEqualTo(Long value) {
            addCriterion("report_id =", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdNotEqualTo(Long value) {
            addCriterion("report_id <>", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdGreaterThan(Long value) {
            addCriterion("report_id >", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdGreaterThanOrEqualTo(Long value) {
            addCriterion("report_id >=", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdLessThan(Long value) {
            addCriterion("report_id <", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdLessThanOrEqualTo(Long value) {
            addCriterion("report_id <=", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdIn(List<Long> values) {
            addCriterion("report_id in", values, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdNotIn(List<Long> values) {
            addCriterion("report_id not in", values, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdBetween(Long value1, Long value2) {
            addCriterion("report_id between", value1, value2, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdNotBetween(Long value1, Long value2) {
            addCriterion("report_id not between", value1, value2, "reportId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jianchaorder
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jianchaorder
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}