package com.iotexample.demo.model;

import java.io.Serializable;

public class Jiuzhen implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhen.jiuzhen_id
     *
     * @mbg.generated
     */
    private Integer jiuzhenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhen.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhen.doctor_name
     *
     * @mbg.generated
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhen.jiuzhen_content
     *
     * @mbg.generated
     */
    private String jiuzhenContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhen.jiuzhen_id
     *
     * @return the value of jiuzhen.jiuzhen_id
     *
     * @mbg.generated
     */
    public Integer getJiuzhenId() {
        return jiuzhenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhen.jiuzhen_id
     *
     * @param jiuzhenId the value for jiuzhen.jiuzhen_id
     *
     * @mbg.generated
     */
    public void setJiuzhenId(Integer jiuzhenId) {
        this.jiuzhenId = jiuzhenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhen.doctor_id
     *
     * @return the value of jiuzhen.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhen.doctor_id
     *
     * @param doctorId the value for jiuzhen.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhen.doctor_name
     *
     * @return the value of jiuzhen.doctor_name
     *
     * @mbg.generated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhen.doctor_name
     *
     * @param doctorName the value for jiuzhen.doctor_name
     *
     * @mbg.generated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhen.jiuzhen_content
     *
     * @return the value of jiuzhen.jiuzhen_content
     *
     * @mbg.generated
     */
    public String getJiuzhenContent() {
        return jiuzhenContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhen.jiuzhen_content
     *
     * @param jiuzhenContent the value for jiuzhen.jiuzhen_content
     *
     * @mbg.generated
     */
    public void setJiuzhenContent(String jiuzhenContent) {
        this.jiuzhenContent = jiuzhenContent == null ? null : jiuzhenContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiuzhen
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jiuzhenId=").append(jiuzhenId);
        sb.append(", doctorId=").append(doctorId);
        sb.append(", doctorName=").append(doctorName);
        sb.append(", jiuzhenContent=").append(jiuzhenContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}