package com.iotexample.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TreatmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table treatment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table treatment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table treatment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public TreatmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table treatment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTreatmentIdIsNull() {
            addCriterion("treatment_id is null");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdIsNotNull() {
            addCriterion("treatment_id is not null");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdEqualTo(Long value) {
            addCriterion("treatment_id =", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdNotEqualTo(Long value) {
            addCriterion("treatment_id <>", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdGreaterThan(Long value) {
            addCriterion("treatment_id >", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("treatment_id >=", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdLessThan(Long value) {
            addCriterion("treatment_id <", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdLessThanOrEqualTo(Long value) {
            addCriterion("treatment_id <=", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdIn(List<Long> values) {
            addCriterion("treatment_id in", values, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdNotIn(List<Long> values) {
            addCriterion("treatment_id not in", values, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdBetween(Long value1, Long value2) {
            addCriterion("treatment_id between", value1, value2, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdNotBetween(Long value1, Long value2) {
            addCriterion("treatment_id not between", value1, value2, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostIsNull() {
            addCriterion("treatment_cost is null");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostIsNotNull() {
            addCriterion("treatment_cost is not null");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostEqualTo(BigDecimal value) {
            addCriterion("treatment_cost =", value, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostNotEqualTo(BigDecimal value) {
            addCriterion("treatment_cost <>", value, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostGreaterThan(BigDecimal value) {
            addCriterion("treatment_cost >", value, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("treatment_cost >=", value, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostLessThan(BigDecimal value) {
            addCriterion("treatment_cost <", value, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("treatment_cost <=", value, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostIn(List<BigDecimal> values) {
            addCriterion("treatment_cost in", values, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostNotIn(List<BigDecimal> values) {
            addCriterion("treatment_cost not in", values, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("treatment_cost between", value1, value2, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andTreatmentCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("treatment_cost not between", value1, value2, "treatmentCost");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdIsNull() {
            addCriterion("medicalRecord_id is null");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdIsNotNull() {
            addCriterion("medicalRecord_id is not null");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdEqualTo(Long value) {
            addCriterion("medicalRecord_id =", value, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdNotEqualTo(Long value) {
            addCriterion("medicalRecord_id <>", value, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdGreaterThan(Long value) {
            addCriterion("medicalRecord_id >", value, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdGreaterThanOrEqualTo(Long value) {
            addCriterion("medicalRecord_id >=", value, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdLessThan(Long value) {
            addCriterion("medicalRecord_id <", value, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdLessThanOrEqualTo(Long value) {
            addCriterion("medicalRecord_id <=", value, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdIn(List<Long> values) {
            addCriterion("medicalRecord_id in", values, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdNotIn(List<Long> values) {
            addCriterion("medicalRecord_id not in", values, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdBetween(Long value1, Long value2) {
            addCriterion("medicalRecord_id between", value1, value2, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordIdNotBetween(Long value1, Long value2) {
            addCriterion("medicalRecord_id not between", value1, value2, "medicalrecordId");
            return (Criteria) this;
        }

        public Criteria andPayStateIsNull() {
            addCriterion("pay_state is null");
            return (Criteria) this;
        }

        public Criteria andPayStateIsNotNull() {
            addCriterion("pay_state is not null");
            return (Criteria) this;
        }

        public Criteria andPayStateEqualTo(Integer value) {
            addCriterion("pay_state =", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotEqualTo(Integer value) {
            addCriterion("pay_state <>", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateGreaterThan(Integer value) {
            addCriterion("pay_state >", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_state >=", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateLessThan(Integer value) {
            addCriterion("pay_state <", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateLessThanOrEqualTo(Integer value) {
            addCriterion("pay_state <=", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateIn(List<Integer> values) {
            addCriterion("pay_state in", values, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotIn(List<Integer> values) {
            addCriterion("pay_state not in", values, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateBetween(Integer value1, Integer value2) {
            addCriterion("pay_state between", value1, value2, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_state not between", value1, value2, "payState");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table treatment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table treatment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}