package com.iotexample.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TreatmentDrugOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public TreatmentDrugOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTreatmentDrugOrderIdIsNull() {
            addCriterion("treatment_drug_order_id is null");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdIsNotNull() {
            addCriterion("treatment_drug_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdEqualTo(Long value) {
            addCriterion("treatment_drug_order_id =", value, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdNotEqualTo(Long value) {
            addCriterion("treatment_drug_order_id <>", value, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdGreaterThan(Long value) {
            addCriterion("treatment_drug_order_id >", value, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("treatment_drug_order_id >=", value, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdLessThan(Long value) {
            addCriterion("treatment_drug_order_id <", value, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("treatment_drug_order_id <=", value, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdIn(List<Long> values) {
            addCriterion("treatment_drug_order_id in", values, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdNotIn(List<Long> values) {
            addCriterion("treatment_drug_order_id not in", values, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdBetween(Long value1, Long value2) {
            addCriterion("treatment_drug_order_id between", value1, value2, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andTreatmentDrugOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("treatment_drug_order_id not between", value1, value2, "treatmentDrugOrderId");
            return (Criteria) this;
        }

        public Criteria andDrugIdIsNull() {
            addCriterion("drug_id is null");
            return (Criteria) this;
        }

        public Criteria andDrugIdIsNotNull() {
            addCriterion("drug_id is not null");
            return (Criteria) this;
        }

        public Criteria andDrugIdEqualTo(Long value) {
            addCriterion("drug_id =", value, "drugId");
            return (Criteria) this;
        }

        public Criteria andDrugIdNotEqualTo(Long value) {
            addCriterion("drug_id <>", value, "drugId");
            return (Criteria) this;
        }

        public Criteria andDrugIdGreaterThan(Long value) {
            addCriterion("drug_id >", value, "drugId");
            return (Criteria) this;
        }

        public Criteria andDrugIdGreaterThanOrEqualTo(Long value) {
            addCriterion("drug_id >=", value, "drugId");
            return (Criteria) this;
        }

        public Criteria andDrugIdLessThan(Long value) {
            addCriterion("drug_id <", value, "drugId");
            return (Criteria) this;
        }

        public Criteria andDrugIdLessThanOrEqualTo(Long value) {
            addCriterion("drug_id <=", value, "drugId");
            return (Criteria) this;
        }

        public Criteria andDrugIdIn(List<Long> values) {
            addCriterion("drug_id in", values, "drugId");
            return (Criteria) this;
        }

        public Criteria andDrugIdNotIn(List<Long> values) {
            addCriterion("drug_id not in", values, "drugId");
            return (Criteria) this;
        }

        public Criteria andDrugIdBetween(Long value1, Long value2) {
            addCriterion("drug_id between", value1, value2, "drugId");
            return (Criteria) this;
        }

        public Criteria andDrugIdNotBetween(Long value1, Long value2) {
            addCriterion("drug_id not between", value1, value2, "drugId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdIsNull() {
            addCriterion("treatment_id is null");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdIsNotNull() {
            addCriterion("treatment_id is not null");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdEqualTo(Long value) {
            addCriterion("treatment_id =", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdNotEqualTo(Long value) {
            addCriterion("treatment_id <>", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdGreaterThan(Long value) {
            addCriterion("treatment_id >", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("treatment_id >=", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdLessThan(Long value) {
            addCriterion("treatment_id <", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdLessThanOrEqualTo(Long value) {
            addCriterion("treatment_id <=", value, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdIn(List<Long> values) {
            addCriterion("treatment_id in", values, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdNotIn(List<Long> values) {
            addCriterion("treatment_id not in", values, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdBetween(Long value1, Long value2) {
            addCriterion("treatment_id between", value1, value2, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andTreatmentIdNotBetween(Long value1, Long value2) {
            addCriterion("treatment_id not between", value1, value2, "treatmentId");
            return (Criteria) this;
        }

        public Criteria andInstructDaysIsNull() {
            addCriterion("instruct_days is null");
            return (Criteria) this;
        }

        public Criteria andInstructDaysIsNotNull() {
            addCriterion("instruct_days is not null");
            return (Criteria) this;
        }

        public Criteria andInstructDaysEqualTo(Integer value) {
            addCriterion("instruct_days =", value, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructDaysNotEqualTo(Integer value) {
            addCriterion("instruct_days <>", value, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructDaysGreaterThan(Integer value) {
            addCriterion("instruct_days >", value, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("instruct_days >=", value, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructDaysLessThan(Integer value) {
            addCriterion("instruct_days <", value, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructDaysLessThanOrEqualTo(Integer value) {
            addCriterion("instruct_days <=", value, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructDaysIn(List<Integer> values) {
            addCriterion("instruct_days in", values, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructDaysNotIn(List<Integer> values) {
            addCriterion("instruct_days not in", values, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructDaysBetween(Integer value1, Integer value2) {
            addCriterion("instruct_days between", value1, value2, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("instruct_days not between", value1, value2, "instructDays");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayIsNull() {
            addCriterion("instruct_count_per_day is null");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayIsNotNull() {
            addCriterion("instruct_count_per_day is not null");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayEqualTo(Integer value) {
            addCriterion("instruct_count_per_day =", value, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayNotEqualTo(Integer value) {
            addCriterion("instruct_count_per_day <>", value, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayGreaterThan(Integer value) {
            addCriterion("instruct_count_per_day >", value, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("instruct_count_per_day >=", value, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayLessThan(Integer value) {
            addCriterion("instruct_count_per_day <", value, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayLessThanOrEqualTo(Integer value) {
            addCriterion("instruct_count_per_day <=", value, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayIn(List<Integer> values) {
            addCriterion("instruct_count_per_day in", values, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayNotIn(List<Integer> values) {
            addCriterion("instruct_count_per_day not in", values, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayBetween(Integer value1, Integer value2) {
            addCriterion("instruct_count_per_day between", value1, value2, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andInstructCountPerDayNotBetween(Integer value1, Integer value2) {
            addCriterion("instruct_count_per_day not between", value1, value2, "instructCountPerDay");
            return (Criteria) this;
        }

        public Criteria andDrugPriceIsNull() {
            addCriterion("drug_price is null");
            return (Criteria) this;
        }

        public Criteria andDrugPriceIsNotNull() {
            addCriterion("drug_price is not null");
            return (Criteria) this;
        }

        public Criteria andDrugPriceEqualTo(BigDecimal value) {
            addCriterion("drug_price =", value, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugPriceNotEqualTo(BigDecimal value) {
            addCriterion("drug_price <>", value, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugPriceGreaterThan(BigDecimal value) {
            addCriterion("drug_price >", value, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("drug_price >=", value, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugPriceLessThan(BigDecimal value) {
            addCriterion("drug_price <", value, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("drug_price <=", value, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugPriceIn(List<BigDecimal> values) {
            addCriterion("drug_price in", values, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugPriceNotIn(List<BigDecimal> values) {
            addCriterion("drug_price not in", values, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("drug_price between", value1, value2, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("drug_price not between", value1, value2, "drugPrice");
            return (Criteria) this;
        }

        public Criteria andDrugCountIsNull() {
            addCriterion("drug_count is null");
            return (Criteria) this;
        }

        public Criteria andDrugCountIsNotNull() {
            addCriterion("drug_count is not null");
            return (Criteria) this;
        }

        public Criteria andDrugCountEqualTo(Integer value) {
            addCriterion("drug_count =", value, "drugCount");
            return (Criteria) this;
        }

        public Criteria andDrugCountNotEqualTo(Integer value) {
            addCriterion("drug_count <>", value, "drugCount");
            return (Criteria) this;
        }

        public Criteria andDrugCountGreaterThan(Integer value) {
            addCriterion("drug_count >", value, "drugCount");
            return (Criteria) this;
        }

        public Criteria andDrugCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("drug_count >=", value, "drugCount");
            return (Criteria) this;
        }

        public Criteria andDrugCountLessThan(Integer value) {
            addCriterion("drug_count <", value, "drugCount");
            return (Criteria) this;
        }

        public Criteria andDrugCountLessThanOrEqualTo(Integer value) {
            addCriterion("drug_count <=", value, "drugCount");
            return (Criteria) this;
        }

        public Criteria andDrugCountIn(List<Integer> values) {
            addCriterion("drug_count in", values, "drugCount");
            return (Criteria) this;
        }

        public Criteria andDrugCountNotIn(List<Integer> values) {
            addCriterion("drug_count not in", values, "drugCount");
            return (Criteria) this;
        }

        public Criteria andDrugCountBetween(Integer value1, Integer value2) {
            addCriterion("drug_count between", value1, value2, "drugCount");
            return (Criteria) this;
        }

        public Criteria andDrugCountNotBetween(Integer value1, Integer value2) {
            addCriterion("drug_count not between", value1, value2, "drugCount");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("total_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("total_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(BigDecimal value) {
            addCriterion("total_price =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("total_price <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("total_price >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_price >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(BigDecimal value) {
            addCriterion("total_price <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_price <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<BigDecimal> values) {
            addCriterion("total_price in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("total_price not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_price between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_price not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table treatment_drug_order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table treatment_drug_order
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}