package com.iotexample.demo.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Xray implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xray.xray_id
     *
     * @mbg.generated
     */
    private Long xrayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xray.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xray.xray_time
     *
     * @mbg.generated
     */
    private Date xrayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xray.xray_addr
     *
     * @mbg.generated
     */
    private String xrayAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xray.xray_cost
     *
     * @mbg.generated
     */
    private BigDecimal xrayCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xray.xray_report
     *
     * @mbg.generated
     */
    private String xrayReport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xray.report_time
     *
     * @mbg.generated
     */
    private Date reportTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xray.xray_img
     *
     * @mbg.generated
     */
    private String xrayImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xray.xray_part
     *
     * @mbg.generated
     */
    private String xrayPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xray
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xray.xray_id
     *
     * @return the value of xray.xray_id
     *
     * @mbg.generated
     */
    public Long getXrayId() {
        return xrayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Xray withXrayId(Long xrayId) {
        this.setXrayId(xrayId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xray.xray_id
     *
     * @param xrayId the value for xray.xray_id
     *
     * @mbg.generated
     */
    public void setXrayId(Long xrayId) {
        this.xrayId = xrayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xray.user_id
     *
     * @return the value of xray.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Xray withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xray.user_id
     *
     * @param userId the value for xray.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xray.xray_time
     *
     * @return the value of xray.xray_time
     *
     * @mbg.generated
     */
    public Date getXrayTime() {
        return xrayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Xray withXrayTime(Date xrayTime) {
        this.setXrayTime(xrayTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xray.xray_time
     *
     * @param xrayTime the value for xray.xray_time
     *
     * @mbg.generated
     */
    public void setXrayTime(Date xrayTime) {
        this.xrayTime = xrayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xray.xray_addr
     *
     * @return the value of xray.xray_addr
     *
     * @mbg.generated
     */
    public String getXrayAddr() {
        return xrayAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Xray withXrayAddr(String xrayAddr) {
        this.setXrayAddr(xrayAddr);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xray.xray_addr
     *
     * @param xrayAddr the value for xray.xray_addr
     *
     * @mbg.generated
     */
    public void setXrayAddr(String xrayAddr) {
        this.xrayAddr = xrayAddr == null ? null : xrayAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xray.xray_cost
     *
     * @return the value of xray.xray_cost
     *
     * @mbg.generated
     */
    public BigDecimal getXrayCost() {
        return xrayCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Xray withXrayCost(BigDecimal xrayCost) {
        this.setXrayCost(xrayCost);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xray.xray_cost
     *
     * @param xrayCost the value for xray.xray_cost
     *
     * @mbg.generated
     */
    public void setXrayCost(BigDecimal xrayCost) {
        this.xrayCost = xrayCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xray.xray_report
     *
     * @return the value of xray.xray_report
     *
     * @mbg.generated
     */
    public String getXrayReport() {
        return xrayReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Xray withXrayReport(String xrayReport) {
        this.setXrayReport(xrayReport);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xray.xray_report
     *
     * @param xrayReport the value for xray.xray_report
     *
     * @mbg.generated
     */
    public void setXrayReport(String xrayReport) {
        this.xrayReport = xrayReport == null ? null : xrayReport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xray.report_time
     *
     * @return the value of xray.report_time
     *
     * @mbg.generated
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Xray withReportTime(Date reportTime) {
        this.setReportTime(reportTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xray.report_time
     *
     * @param reportTime the value for xray.report_time
     *
     * @mbg.generated
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xray.xray_img
     *
     * @return the value of xray.xray_img
     *
     * @mbg.generated
     */
    public String getXrayImg() {
        return xrayImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Xray withXrayImg(String xrayImg) {
        this.setXrayImg(xrayImg);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xray.xray_img
     *
     * @param xrayImg the value for xray.xray_img
     *
     * @mbg.generated
     */
    public void setXrayImg(String xrayImg) {
        this.xrayImg = xrayImg == null ? null : xrayImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xray.xray_part
     *
     * @return the value of xray.xray_part
     *
     * @mbg.generated
     */
    public String getXrayPart() {
        return xrayPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Xray withXrayPart(String xrayPart) {
        this.setXrayPart(xrayPart);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xray.xray_part
     *
     * @param xrayPart the value for xray.xray_part
     *
     * @mbg.generated
     */
    public void setXrayPart(String xrayPart) {
        this.xrayPart = xrayPart == null ? null : xrayPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xrayId=").append(xrayId);
        sb.append(", userId=").append(userId);
        sb.append(", xrayTime=").append(xrayTime);
        sb.append(", xrayAddr=").append(xrayAddr);
        sb.append(", xrayCost=").append(xrayCost);
        sb.append(", xrayReport=").append(xrayReport);
        sb.append(", reportTime=").append(reportTime);
        sb.append(", xrayImg=").append(xrayImg);
        sb.append(", xrayPart=").append(xrayPart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}