package com.iotexample.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XrayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xray
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xray
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xray
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public XrayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xray
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xray
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andXrayIdIsNull() {
            addCriterion("xray_id is null");
            return (Criteria) this;
        }

        public Criteria andXrayIdIsNotNull() {
            addCriterion("xray_id is not null");
            return (Criteria) this;
        }

        public Criteria andXrayIdEqualTo(Long value) {
            addCriterion("xray_id =", value, "xrayId");
            return (Criteria) this;
        }

        public Criteria andXrayIdNotEqualTo(Long value) {
            addCriterion("xray_id <>", value, "xrayId");
            return (Criteria) this;
        }

        public Criteria andXrayIdGreaterThan(Long value) {
            addCriterion("xray_id >", value, "xrayId");
            return (Criteria) this;
        }

        public Criteria andXrayIdGreaterThanOrEqualTo(Long value) {
            addCriterion("xray_id >=", value, "xrayId");
            return (Criteria) this;
        }

        public Criteria andXrayIdLessThan(Long value) {
            addCriterion("xray_id <", value, "xrayId");
            return (Criteria) this;
        }

        public Criteria andXrayIdLessThanOrEqualTo(Long value) {
            addCriterion("xray_id <=", value, "xrayId");
            return (Criteria) this;
        }

        public Criteria andXrayIdIn(List<Long> values) {
            addCriterion("xray_id in", values, "xrayId");
            return (Criteria) this;
        }

        public Criteria andXrayIdNotIn(List<Long> values) {
            addCriterion("xray_id not in", values, "xrayId");
            return (Criteria) this;
        }

        public Criteria andXrayIdBetween(Long value1, Long value2) {
            addCriterion("xray_id between", value1, value2, "xrayId");
            return (Criteria) this;
        }

        public Criteria andXrayIdNotBetween(Long value1, Long value2) {
            addCriterion("xray_id not between", value1, value2, "xrayId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andXrayTimeIsNull() {
            addCriterion("xray_time is null");
            return (Criteria) this;
        }

        public Criteria andXrayTimeIsNotNull() {
            addCriterion("xray_time is not null");
            return (Criteria) this;
        }

        public Criteria andXrayTimeEqualTo(Date value) {
            addCriterion("xray_time =", value, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayTimeNotEqualTo(Date value) {
            addCriterion("xray_time <>", value, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayTimeGreaterThan(Date value) {
            addCriterion("xray_time >", value, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("xray_time >=", value, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayTimeLessThan(Date value) {
            addCriterion("xray_time <", value, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayTimeLessThanOrEqualTo(Date value) {
            addCriterion("xray_time <=", value, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayTimeIn(List<Date> values) {
            addCriterion("xray_time in", values, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayTimeNotIn(List<Date> values) {
            addCriterion("xray_time not in", values, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayTimeBetween(Date value1, Date value2) {
            addCriterion("xray_time between", value1, value2, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayTimeNotBetween(Date value1, Date value2) {
            addCriterion("xray_time not between", value1, value2, "xrayTime");
            return (Criteria) this;
        }

        public Criteria andXrayAddrIsNull() {
            addCriterion("xray_addr is null");
            return (Criteria) this;
        }

        public Criteria andXrayAddrIsNotNull() {
            addCriterion("xray_addr is not null");
            return (Criteria) this;
        }

        public Criteria andXrayAddrEqualTo(String value) {
            addCriterion("xray_addr =", value, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrNotEqualTo(String value) {
            addCriterion("xray_addr <>", value, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrGreaterThan(String value) {
            addCriterion("xray_addr >", value, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrGreaterThanOrEqualTo(String value) {
            addCriterion("xray_addr >=", value, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrLessThan(String value) {
            addCriterion("xray_addr <", value, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrLessThanOrEqualTo(String value) {
            addCriterion("xray_addr <=", value, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrLike(String value) {
            addCriterion("xray_addr like", value, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrNotLike(String value) {
            addCriterion("xray_addr not like", value, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrIn(List<String> values) {
            addCriterion("xray_addr in", values, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrNotIn(List<String> values) {
            addCriterion("xray_addr not in", values, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrBetween(String value1, String value2) {
            addCriterion("xray_addr between", value1, value2, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayAddrNotBetween(String value1, String value2) {
            addCriterion("xray_addr not between", value1, value2, "xrayAddr");
            return (Criteria) this;
        }

        public Criteria andXrayCostIsNull() {
            addCriterion("xray_cost is null");
            return (Criteria) this;
        }

        public Criteria andXrayCostIsNotNull() {
            addCriterion("xray_cost is not null");
            return (Criteria) this;
        }

        public Criteria andXrayCostEqualTo(BigDecimal value) {
            addCriterion("xray_cost =", value, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayCostNotEqualTo(BigDecimal value) {
            addCriterion("xray_cost <>", value, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayCostGreaterThan(BigDecimal value) {
            addCriterion("xray_cost >", value, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("xray_cost >=", value, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayCostLessThan(BigDecimal value) {
            addCriterion("xray_cost <", value, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("xray_cost <=", value, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayCostIn(List<BigDecimal> values) {
            addCriterion("xray_cost in", values, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayCostNotIn(List<BigDecimal> values) {
            addCriterion("xray_cost not in", values, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("xray_cost between", value1, value2, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("xray_cost not between", value1, value2, "xrayCost");
            return (Criteria) this;
        }

        public Criteria andXrayReportIsNull() {
            addCriterion("xray_report is null");
            return (Criteria) this;
        }

        public Criteria andXrayReportIsNotNull() {
            addCriterion("xray_report is not null");
            return (Criteria) this;
        }

        public Criteria andXrayReportEqualTo(String value) {
            addCriterion("xray_report =", value, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportNotEqualTo(String value) {
            addCriterion("xray_report <>", value, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportGreaterThan(String value) {
            addCriterion("xray_report >", value, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportGreaterThanOrEqualTo(String value) {
            addCriterion("xray_report >=", value, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportLessThan(String value) {
            addCriterion("xray_report <", value, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportLessThanOrEqualTo(String value) {
            addCriterion("xray_report <=", value, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportLike(String value) {
            addCriterion("xray_report like", value, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportNotLike(String value) {
            addCriterion("xray_report not like", value, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportIn(List<String> values) {
            addCriterion("xray_report in", values, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportNotIn(List<String> values) {
            addCriterion("xray_report not in", values, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportBetween(String value1, String value2) {
            addCriterion("xray_report between", value1, value2, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andXrayReportNotBetween(String value1, String value2) {
            addCriterion("xray_report not between", value1, value2, "xrayReport");
            return (Criteria) this;
        }

        public Criteria andReportTimeIsNull() {
            addCriterion("report_time is null");
            return (Criteria) this;
        }

        public Criteria andReportTimeIsNotNull() {
            addCriterion("report_time is not null");
            return (Criteria) this;
        }

        public Criteria andReportTimeEqualTo(Date value) {
            addCriterion("report_time =", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeNotEqualTo(Date value) {
            addCriterion("report_time <>", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeGreaterThan(Date value) {
            addCriterion("report_time >", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("report_time >=", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeLessThan(Date value) {
            addCriterion("report_time <", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeLessThanOrEqualTo(Date value) {
            addCriterion("report_time <=", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeIn(List<Date> values) {
            addCriterion("report_time in", values, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeNotIn(List<Date> values) {
            addCriterion("report_time not in", values, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeBetween(Date value1, Date value2) {
            addCriterion("report_time between", value1, value2, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeNotBetween(Date value1, Date value2) {
            addCriterion("report_time not between", value1, value2, "reportTime");
            return (Criteria) this;
        }

        public Criteria andXrayImgIsNull() {
            addCriterion("xray_img is null");
            return (Criteria) this;
        }

        public Criteria andXrayImgIsNotNull() {
            addCriterion("xray_img is not null");
            return (Criteria) this;
        }

        public Criteria andXrayImgEqualTo(String value) {
            addCriterion("xray_img =", value, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgNotEqualTo(String value) {
            addCriterion("xray_img <>", value, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgGreaterThan(String value) {
            addCriterion("xray_img >", value, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgGreaterThanOrEqualTo(String value) {
            addCriterion("xray_img >=", value, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgLessThan(String value) {
            addCriterion("xray_img <", value, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgLessThanOrEqualTo(String value) {
            addCriterion("xray_img <=", value, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgLike(String value) {
            addCriterion("xray_img like", value, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgNotLike(String value) {
            addCriterion("xray_img not like", value, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgIn(List<String> values) {
            addCriterion("xray_img in", values, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgNotIn(List<String> values) {
            addCriterion("xray_img not in", values, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgBetween(String value1, String value2) {
            addCriterion("xray_img between", value1, value2, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayImgNotBetween(String value1, String value2) {
            addCriterion("xray_img not between", value1, value2, "xrayImg");
            return (Criteria) this;
        }

        public Criteria andXrayPartIsNull() {
            addCriterion("xray_part is null");
            return (Criteria) this;
        }

        public Criteria andXrayPartIsNotNull() {
            addCriterion("xray_part is not null");
            return (Criteria) this;
        }

        public Criteria andXrayPartEqualTo(String value) {
            addCriterion("xray_part =", value, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartNotEqualTo(String value) {
            addCriterion("xray_part <>", value, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartGreaterThan(String value) {
            addCriterion("xray_part >", value, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartGreaterThanOrEqualTo(String value) {
            addCriterion("xray_part >=", value, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartLessThan(String value) {
            addCriterion("xray_part <", value, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartLessThanOrEqualTo(String value) {
            addCriterion("xray_part <=", value, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartLike(String value) {
            addCriterion("xray_part like", value, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartNotLike(String value) {
            addCriterion("xray_part not like", value, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartIn(List<String> values) {
            addCriterion("xray_part in", values, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartNotIn(List<String> values) {
            addCriterion("xray_part not in", values, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartBetween(String value1, String value2) {
            addCriterion("xray_part between", value1, value2, "xrayPart");
            return (Criteria) this;
        }

        public Criteria andXrayPartNotBetween(String value1, String value2) {
            addCriterion("xray_part not between", value1, value2, "xrayPart");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xray
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xray
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}